### ISSUE TITLE
Unneeded code and simplification suggestion for Logistic Regressor

### ISSUE THREAD

**Issue by snowthesprite** [anton-perez/machine-learning#10]
I noticed that in several of your files you have the 
```
import sys
sys.path.append('src')
```
But you only really need that in files that are not in the 'src' folder, otherwise you can just skip that part and use the import. Asides from that I noticed you also import assisting (classes? functions? its the things like `from matrix import Matrix`). In general, you only need to state that you import those if your actually going to make a thing from that class. other functions will work just fine without you stating it if its already stated in the class your using, say the Linear Regressor and Dataframe with the Matrix class. You don't really need to state the matrix as your not making a matrix. Finally, you could probably simplify your Logistic Regressor by making it a child class of the Linear regressor. Plus then when you need to make a change, you only have to do it once.

**Comment by anton-perez** [comment]
Thank you, I'll keep that in mind moving forward.
