### ISSUE TITLE
8_queens optional simplification

### ISSUE THREAD

**Issue by snowthesprite** [anton-perez/machine-learning#7]
Your codes actually pretty good and I can't find much wrong with it other than personal preference. However, I'm fairly certain that we're going to be doing random numbers again, so I'm just gonna say that your locations_list is a mess and it took me a while to figure out what's going on there. You can replace your `math.floor(9*rand.random())` with `rand.randint(0,8)`. This is a method in the random library that will give a random integer between 0 and 8, edges included. Its a meh, and you don't have to change it,  but it might make life easier down the line.

**Comment by anton-perez** [comment]
I think I'll leave it as is, but I'll consider that in the future.
